TARGET = 'GSRDApp'
SOURCES  = ['GSRDApp.cpp']
RESOURCES = ['gsrd_frag.glsl', 'passthru_vert.glsl', 'redlum_frag.glsl', 'seed_frag.glsl']

SOURCES += ['GaussianBlur.cpp']
RESOURCES += ['blurh11_vert.glsl', 'blurv11_vert.glsl', 
		'blurh11_frag.glsl', 'blurv11_frag.glsl']

SOURCES += ['Sobel.cpp']
RESOURCES += ['sobel_frag.glsl']

SOURCES += ['FreiChen.cpp']
RESOURCES += ['freichen_frag.glsl']

RESOURCES += ['envmap_frag.glsl', 'envmap.jpg']

DEBUG = 0

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'DEBUG', 'RESOURCES'])

