env = Environment()

env['APP_TARGET'] = 'GSRDApp'
env['APP_SOURCES']  = ['GSRDApp.cpp']
env['RESOURCES'] = ['gsrd_frag.glsl', 'passthru_vert.glsl', 'redlum_frag.glsl', 'seed_frag.glsl']

env['APP_SOURCES'] += ['GaussianBlur.cpp']
env['RESOURCES'] += ['blurh11_vert.glsl', 'blurv11_vert.glsl',
					'blurh11_frag.glsl', 'blurv11_frag.glsl']

env['APP_SOURCES'] += ['Sobel.cpp']
env['RESOURCES'] += ['sobel_frag.glsl']

env['APP_SOURCES'] += ['FreiChen.cpp']
env['RESOURCES'] += ['freichen_frag.glsl']

env['RESOURCES'] += ['envmap_frag.glsl', 'envmap.jpg']

env['DEBUG'] = 0

SConscript('../../../scons/SConscript', exports = 'env')

