env = Environment()

env['APP_TARGET'] = 'TrackerApp'
env['APP_SOURCES'] = ['TrackerApp.cpp', 'NIBlobTracker.cpp']
env['DEBUG'] = 1

env = SConscript('../../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/MndlKit/scons/SConscript', exports = 'env')

SConscript('../../../../scons/SConscript', exports = 'env')

