env = Environment()

env['APP_TARGET'] = 'KaleidoscopeApp'
env['APP_SOURCES'] = ['KaleidoscopeApp.cpp']
env['ASSETS'] = ['Kaleidoscope.frag', 'Kaleidoscope.vert', 'tx.jpg']
env['DEBUG'] = 1

SConscript('../../../scons/SConscript', exports = 'env')

