env = Environment()

env['APP_TARGET'] = 'DynaApp'
env['APP_SOURCES'] = ['DynaApp.cpp', 'Particles.cpp', 'DynaStroke.cpp']
env['RESOURCES'] = ['KawaseBloom.vert', 'KawaseBloom.frag', 'brush.png']
env['DEBUG'] = 0

env = SConscript('../../../blocks/msaFluid/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')

