MSAFLUID_PATH = '../../../blocks/msaFluid/scons/'
CINDER_OPENCV_PATH = '../../../blocks/Cinder-OpenCV/scons/'

# msaFluid
import sys
sys.path.append(MSAFLUID_PATH)
import msaFluid
SOURCES = msaFluid.getSources(MSAFLUID_PATH)
INCLUDES = msaFluid.getIncludes(MSAFLUID_PATH)

# OpenCV
sys.path.append(CINDER_OPENCV_PATH)
import CinderOpenCV
SOURCES += CinderOpenCV.getSources(CINDER_OPENCV_PATH)
INCLUDES += CinderOpenCV.getIncludes(CINDER_OPENCV_PATH)
LIBS = CinderOpenCV.getLibs(CINDER_OPENCV_PATH)
LIBS = [File(s) for s in LIBS]

# OpenNI
INCLUDES += ['/usr/include/ni/', '/usr/include/nite/']
LIBS += ['OpenNI', 'usb-1.0']
LIBPATH = ['/usr/lib/', '/opt/local/lib/']

TARGET = 'Akac'
SOURCES += ['Acacia.cpp', 'PParams.cpp', 'Leaves.cpp', 'NI.cpp']
ASSETS = [ 'bw' ]
DEBUG = 0

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'INCLUDES', 'ASSETS', \
			'LIBS', 'LIBPATH', 'DEBUG'])

