env = Environment()

env['APP_TARGET'] = 'NIUserContourApp'
env['APP_SOURCES'] = ['NIUserContourApp.cpp']
env['RESOURCES'] = ['line.*']
env['DEBUG'] = 1

env = SConscript('../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')

