TARGET = 'PageCurlApp'
SOURCES  = ['PageCurl.cpp', 'PageCurlApp.cpp']
RESOURCES = ['book', 'gfx', 'sfx']
DEBUG = 1

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'DEBUG', 'RESOURCES'])

