import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})

env['APP_TARGET'] = 'KotoKaori'
env['APP_SOURCES'] = ['KotoKaoriApp.cpp', 'PParams.cpp', 'Effect.cpp',
		'NI.cpp', 'Utils.cpp']
env['RESOURCES'] = []
env['ASSETS'] = []
env['ICON'] = 'koto.icns'

# KezekLabak
env['APP_SOURCES'] += [ 'DepthMerge.cpp' ]
env['RESOURCES'] += ['PassThroughVert.glsl', 'DepthMergeFrag.glsl']

# BeszedBolt
env['APP_SOURCES'] += [ 'SpeechShop.cpp' ]
env['ASSETS'] += [ 'BeszedBolt' ]

# Akac
env['APP_SOURCES'] += [ 'Acacia.cpp', 'Leaves.cpp', 'Particles.cpp' ]
env['ASSETS'] += [ 'Akac' ]
env['RESOURCES'] += ['BloomFrag.glsl']

# Hold
env['APP_SOURCES'] += [ 'Moon.cpp' ]
env['ASSETS'] += [ 'Hold' ]

# Varos es termeszet
env['APP_SOURCES'] += [ 'VTT.cpp' ]
env['ASSETS'] += [ 'VarosEsTermeszet' ]

env['DEBUG'] = 0

env = SConscript('../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/sc-Box2D/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/msaFluid/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
