env = Environment()

env['APP_TARGET'] = 'VoronoiGridApp'
env['APP_SOURCES'] = ['VoronoiGridApp.cpp', 'HomogeneousRectangularGridTorsion.cpp',
		'HomogeneousTriangleGridTorsion.cpp']
env['DEBUG'] = 0

SConscript('../../../scons/SConscript', exports = 'env')

