TARGET = 'KinectGSRDApp'
SOURCES  = ['KinectGSRDApp.cpp']
RESOURCES = ['gsrd_frag.glsl', 'passthru_vert.glsl', 'redlum_frag.glsl', 'seed_frag.glsl']

SOURCES += ['GaussianBlur.cpp']
RESOURCES += ['blurh11_vert.glsl', 'blurv11_vert.glsl', 
		'blurh11_frag.glsl', 'blurv11_frag.glsl']

RESOURCES += ['envmap_frag.glsl', 'envmap.jpg']

BLOCKS = ['kinect']

DEBUG = 0

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'DEBUG', 'RESOURCES', 'BLOCKS'])

