TARGET = 'FilterApp'
SOURCES  = ['FilterApp.cpp']

SOURCES += ['GaussianBlur.cpp']
RESOURCES = ['blurh11_vert.glsl', 'blurv11_vert.glsl', 
		'blurh11_frag.glsl', 'blurv11_frag.glsl']

SOURCES += ['Sobel.cpp']
RESOURCES += ['sobel_frag.glsl']

SOURCES += ['FreiChen.cpp']
RESOURCES += ['passthrough_vert.glsl', 'freichen_frag.glsl']

SOURCES += ['BoxBlur.cpp']
RESOURCES += ['boxblur_frag.glsl']

SOURCES += ['Sharpen.cpp']

SOURCES += ['KawaseBloom.cpp']

DEBUG = 1

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'DEBUG', 'RESOURCES'])

