TARGET = 'KinectCalibrationApp'
SOURCES  = ['KinectCalibrationApp.cpp', 'CameraCalibration.cpp']
BLOCKS = ['opencv', 'kinect']
DEBUG = 1

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'DEBUG', 'BLOCKS'])

