TARGET = 'AssimpApp'
SOURCES  = ['AssimpApp.cpp', 'AssimpLoader.cpp']
RESOURCES = ['fels.3ds', 'seymour.dae']
BLOCKS = ['assimp']
DEBUG = 1

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'DEBUG', 'RESOURCES', 'BLOCKS'])

