env = Environment()

env['APP_TARGET'] = 'KinectReader'
env['APP_SOURCES'] = ['PageCurl.cpp', 'KinectReader.cpp', 'KinectTracker.cpp']
env['RESOURCES'] = ['book/*', 'gfx/*', 'sfx/*', 'ui/*', 'ui-sfx/*', 'logo.png']
env['DEBUG'] = 0

env = SConscript('../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-Kinect/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')

