env = Environment()

env['APP_TARGET'] = 'Voronoi'
env['APP_SOURCES'] = ['Room.cpp', 'Voronoi.cpp']
env['APP_SOURCES'] += ['NIBlobTracker.cpp']
env['ASSETS'] = ['model/chair.obj']
env['DEBUG'] = 0

env = SConscript('../../../../blocks/MndlKit/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')

SConscript('../../../../scons/SConscript', exports = 'env')

