env = Environment()

env['APP_TARGET'] = 'DofTest'
env['APP_SOURCES'] = ['DofTest.cpp', 'CubeMap.cpp']
env['ASSETS'] = ['sphere.obj', 'cubemap/*', 'shaders/*']
env['DEBUG'] = 0

SConscript('../../../scons/SConscript', exports = 'env')

