env = Environment()

env['APP_TARGET'] = 'fsExperiments'
env['APP_SOURCES'] = ['fsExperiments.cpp', 'PParams.cpp', 'Android.cpp',
					'Devil.cpp']
env['ASSETS'] = ['export/*.trimesh', 'loki2.png']
#env['ASSETS'] = ['export/*.obj', 'loki2.png']
env['ASSETS'] += ['models/*']
env['RESOURCES'] = ['Blend.vert', 'Blend.frag']
env['DEBUG'] = 1

env = SConscript('../../../blocks/ciFaceShift/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-Assimp/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
