env = Environment()

env['APP_TARGET'] = 'ChargesApp'
env['APP_SOURCES'] = ['AdarKutta.cpp', 'Charge.cpp', 'ChargesApp.cpp',
	'EffectCharge.cpp', 'KawaseBloom.cpp', 'Particle.cpp']
env['ASSETS'] = ['charge.ogg']
env['ICON'] = '../xcode/charges.icns'
env['DEBUG'] = 0

env = SConscript('../../../blocks/Cinder-LeapSdk/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/MndlKit/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-OpenAL/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')

