TARGET = 'LiquidApp'
SOURCES  = ['LiquidApp.cpp', 'Sharpen.cpp', 'KawaseBloom.cpp']
RESOURCES = ['kibu_logo_png_1024x768.png', 'PassThrough.vert',
		'PhotoshopMath.frag']

DEBUG = 0

# OpenCV
CINDER_OPENCV_PATH = '../../../blocks/Cinder-OpenCV/scons/'

import sys
sys.path.append(CINDER_OPENCV_PATH)
import CinderOpenCV
SOURCES += CinderOpenCV.getSources(CINDER_OPENCV_PATH)
INCLUDES = CinderOpenCV.getIncludes(CINDER_OPENCV_PATH)
LIBS = CinderOpenCV.getLibs(CINDER_OPENCV_PATH)
LIBS = [File(s) for s in LIBS]

SConscript('../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'RESOURCES', 'DEBUG', 'INCLUDES', 'LIBS'])

