env = Environment()

env['APP_TARGET'] = 'LiquidIR'
env['APP_SOURCES'] = ['LiquidKoln.cpp', 'KawaseBloom.cpp', 'PParams.cpp']
env['ASSETS'] = [ 'mask.png' ]
env['DEBUG'] = 0

# OpenCV
env = SConscript('../../../blocks/Cinder-OpenCV/scons/SConscript',
	exports = 'env')

# Syphon
env = SConscript('../../../blocks/Cinder-Syphon/scons/SConscript',
		exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
